config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do 
   shallow do 
    resources :parks do 
      resources :trails
      end 
     end 
    end 

     
         
      resources :trails do
        #shallow do
        resources :comments
   # end
   
  end

  resources :parks, only: [:index]

  resources :trails, only: [:index, :create] 

  get '/trails_by_distance' => 'trails#trails_by_distance'
  get '/trails_by_difficulty' => 'trails#trails_by_difficulty'
  get '/parks_by_location' => 'parks#parks_by_location'
  get '/parks_by_name' => 'parks#parks_by_name'
  get '/trails/:id/next', to: 'trails#next_trail'
  get '/trails/:id/previous', to: 'trails#previous_trail'

  get '/parks/:id/next', to: 'parks#next_park'
  get '/parks/:id/previous', to: 'parks#previous_park'



 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/facebook/callback' => 'sessions#facebook'
  #get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  

end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :user
  has_many :trails, :dependent => :destroy
 
  validates :name, presence: true

  mount_uploader :image, ImageUploader
 

  def self.search(search)
   # where("location LIKE ? ", "#{search}")
    where("cast(location as text) LIKE ? ", "#{search}")
  end

  def self.search4(search)
    #where("name LIKE ? ", "#{search}")
    where("cast(name as text) LIKE ? ", "#{search}")
  end

  def next
    # if the first trail is greater the current one exists then return the next trail
    if next_park = self.class.where("id > ?", id).first
      next_park
    else
     Park.first
    end
  end
  
  def previous
    # if the trail is less then current one exists then return the previous trail
    if previous_park = self.class.where("id < ?", id).last
      previous_park
    else
      Park.last
    end
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
        
    before_action :set_park, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:index]
    def index 
        @parks = Park.all 
        respond_to do |format|
            format.html { render :index }
            format.json { render json:  @parks }
        end
    end 

    def show 
       
        respond_to do |format|
            format.html { render :show }
            format.json { render json:  @park }  
        end  
        
    end 

    def new
        @park = Park.new
    end 

    def create 
        
        @park = current_user.parks.build(park_params)
        if @park.save
            flash[:msg] = "Park created!"
            redirect_to park_path(@park)
        else
            render :new 
        end
    end 

    def next_park
        @park = Park.find(params[:id])
        @next_park = @park.next
        render json: @next_park
      end
  
      def previous_park
        @park = Park.find(params[:id])
        @previous_park = @park.previous
        render json: @previous_park
      end
    

    def edit 
       
    end
    def update
        
        @park = current_user.parks.find(params[:id])
        if @park.update(park_params)
        flash[:msg] = "Park updated."
        redirect_to park_path(@park)
        end 
    end 

    def parks_by_location
        list = Park.search(params[:search]).order("created_at DESC")
        if !list.empty?
          @parks = list
        else
          flash[:notice] = "There are no parks matching the input."
          redirect_to parks_path
        end
      end

      def parks_by_name
        list = Park.search4(params[:search]).order("created_at DESC")
        if !list.empty?
          @parks = list
        else
          flash[:notice] = "There are no parks matching the input."
          redirect_to parks_path
        end
      end

    def destroy
        @park = current_user.parks.find(params[:id])
        @park.destroy
        flash[:msg] = "Park deleted!"
        redirect_to parks_path
    end 

    private 

    def set_park
        @park = Park.find(params[:id]) 

    end 
    def park_params
        params.require(:park).permit(:name, :location, :image, :remove_image, :user_id)
      end




end

app/helpers/parks_helper.rb
module ParksHelper

end

app/views/parks/edit.html.erb
<center><h1> Edit Park </h1></center>
<div class='parks-form'>
<%= form_for (@park) do |f| %>
  <div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :location %><br>
  <%= f.text_field :location %>
</div>
<div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
    <%= image_tag f.object.image.url %>
    <%= f.label :remove_image %>
    <%= f.check_box :remove_image %>
    
   
  <% end %><br><br>
<%= f.hidden_field :user_id, :value => current_user.id%>
      <%= f.submit "Submit", class:"submit" %>
<% end %>

</div>

app/views/parks/index.html.erb
<div class='park-info'>
<div class='wrapper'>
<h1>All Parks</h1>

<% @parks.each do |park| %>
<div id='park'>
<h2>Park Name: <%= link_to park.name, park_path(park), class:'name' %></h2>

<h4>Posted by: <%= link_to park.user.name, user_path(park.user) %></h4>

<% if current_user == park.user %>


<%= link_to "Edit Park", edit_park_path(park), class: "edit-link" %> |
<%= link_to "New trails", new_park_trail_path(park) %> |
     <%= link_to "Delete Park", park_path(park), method: :delete, data: { confirm: 'Are you sure?' }%>
<% end %>

</br>
</div>
<hr />
<% end %>
</div>

 

app/views/parks/new.html.erb
<center><h1>Add a new park</h1></center>
<div class='parks-form'>
<%= form_for ([current_user, @park]) do |f| %>
  <div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :location %><br>
  <%= f.text_field :location %>
</div>

<div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
    <%= image_tag f.object.image.url %>
    <%= f.label :remove_image %>
    <%= f.check_box :remove_image %>
    
   
  <% end %><br><br>
<%= f.hidden_field :user_id, :value => current_user.id%>
      <%= f.submit "Submit", class:"submit" %>
<% end %>



<% if @park.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p> Error: </p>
          <ul>
            <% @park.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
       <% end %>


    </div>

app/views/parks/parks_by_location.html.erb
<h2>Parks by location:</h2><br><br>
<div class = "container">
<% @parks.order("created_at asc").each do |park| %>
  <div class="row row-flex">
      <div class="col-md-6"><br></br>
        <%= image_tag park.image.url(:medium) if park.image? %><br><br>
       
      </div>

     

      <div class="col-md-4 ">
      <h4 class='user-link'>User: <%= link_to park.user.name, user_path(park.user) %></h4>
        <h3>Park:&nbsp;&nbsp;&nbsp; <%= link_to park.name, park_path(park), class:'name' %></h3><br><br>
        
     
    </div>
    
    </div>
    <hr />
<% end %>


</div>

app/views/parks/parks_by_name.html.erb
<h2>Parks by name:</h2><br><br>
<div class = "container">
<% @parks.order("created_at asc").each do |park| %>
  <div class="row row-flex">
      <div class="col-md-6"><br></br>
        <%= image_tag park.image.url(:medium) if park.image? %><br><br>
       
      </div>

     

      <div class="col-md-4 ">
      <h4 class='user-link'>User: <%= link_to park.user.name, user_path(park.user) %></h4>
        <h3>Park:&nbsp;&nbsp;&nbsp; <%= link_to park.name, park_path(park), class:'name' %></h3><br><br>
        
      
    </div>
  </div>
  <hr />
<% end %>
</div>

app/views/parks/show.html.erb
<h2><a href="#" class="js-next-park btn btn-secondary glyphicon glyphicon-chevron-right" style="float: right;" data-id="<%=@park.id%>"></a></h2>
<h2><a href="#" class="js-previous-park btn btn-secondary glyphicon glyphicon-chevron-left" style="float: left;" data-id="<%=@park.id%>"></span></a></h2>

<div class='wrapper-park'>
<header class='park-header'>
<center>
<h1> Park Name: <%= @park.name %></h1>
 <h3 class="item1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Location: &nbsp;&nbsp;&nbsp;<%= @park.location %></h3><br>
</center>
</header>
 

<div class="container-fluid">   

 <div class="row">

 <div class="col-md-8" id='parkImage' style= 'float: right; '>
     
     <%= image_tag @park.image.url(:medium) if @park.image? %>
     </div>
     
      
     
     
   </br>
   <h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trails:</h2>
     <div class="col-md-4" id="park">
     <center>
    <% @park.trails.each do |trail|%>

  <h3><%= link_to trail.name, trail_path(trail) %></h3>
 
   <% end %>
   </center>
   </div>
   </div>
   </div>
   </div>