config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do 
   shallow do 
    resources :parks do 
      resources :trails
      end 
     end 
    end 

     
         
      resources :trails do
        #shallow do
        resources :comments
   # end
   
  end

  resources :parks, only: [:index]

  resources :trails, only: [:index, :create] 

  get '/trails_by_distance' => 'trails#trails_by_distance'
  get '/trails_by_difficulty' => 'trails#trails_by_difficulty'
  get '/parks_by_location' => 'parks#parks_by_location'
  get '/parks_by_name' => 'parks#parks_by_name'
  get '/trails/:id/next', to: 'trails#next_trail'
  get '/trails/:id/previous', to: 'trails#previous_trail'

  get '/parks/:id/next', to: 'parks#next_park'
  get '/parks/:id/previous', to: 'parks#previous_park'



 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/facebook/callback' => 'sessions#facebook'
  #get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
   # validates :password, :confirmation => true #password_confirmation attr
   #validates_length_of :password, :in => 6..60, :on => :create

    has_many :parks, :dependent => :destroy
    has_many :comments, :dependent => :destroy
    has_many :trails, through: :comments
   
    def self.find_or_create_by_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password_digest = SecureRandom.hex
      user.name = auth.info.name
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
   
    def new
     @user = User.new
    end
    
      def show
        @user = User.find(params[:id])
        respond_to do |format|
          format.html { render :show }
          format.json { render json:  @user }    
        end
      end
    
      def create
        @user = User.new(user_params)
    
           if @user.save
             session[:user_id] = @user.id
             redirect_to user_path(@user)
             flash[:msg] = "Welcome to Parks-book."
           else
             render :new
           end
         end
      
    
      private 
    
      def user_params
        params.require(:user).permit(:name, :email, :password)
      end 
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<center>
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
       <div class="form-group">
        <label for="username">Name:</label><br>     
        <%= f.text_field :name, placeholder: "name" %><br>
        </div>
        <div class="form-group">
        <label for="email">Email address:</label><br>
        <%= f.email_field :email, placeholder: "Email" %>
        </div>
        <div class="form-group">
        <label for="pwd">Password:</label><br>
        <%= f.password_field :password, placeholder: "Password (6 char min)" %><br><br>
        </div>
        <%= f.submit "Submit" %>
        </div>

      <% end %>

      <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p> Sign Up Failed: </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
       <% end %>
    </div>

app/views/users/show.html.erb
<div class = 'users'>
<div class='wrapper'>
<% if current_user == @user %>
    <h1 class="card-title">Hello <%= @user.name %>!</h1>
  <% else %>
    <h1 class="card-title"><%=@user.name%>'s profile page</h1>
  <% end %>
<% if @user == current_user %>
 <h2> You have logged <%= "#{@user.parks.size}"%> park(s)</h2>
 <% else %>
 <h2>Parks logged: <%= "#{@user.parks.size}" %></h2>
<% end %>
<div id='parks'>
<a href="#" class="js-view-parks-sort btn btn-primary btn-lg" data_id="<%=@user.id%>"> View Parks </a>

<% @user.parks.each do |park| %>
    
    
   


<% end %>
</div>
<div class="container" style="width:80%;">
  <div class="usersParks">
  </div>
</div>
<br></br>

<% if @user == current_user %>
<h3><%= link_to "Add a Park", new_user_park_path(@user) %></h3>

<% end %>



  <h3>Need some inspiration to decide your next journey? Check out this video!</h3>
<div class="embed-responsive embed-responsive-16by9">
<iframe width="560" height="315" src="https://www.youtube.com/embed/0iqF2Tk_1WA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>