config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do 
   shallow do 
    resources :parks do 
      resources :trails
      end 
     end 
    end 

     
         
      resources :trails do
        #shallow do
        resources :comments
   # end
   
  end

  resources :parks, only: [:index]

  resources :trails, only: [:index, :create] 

  get '/trails_by_distance' => 'trails#trails_by_distance'
  get '/trails_by_difficulty' => 'trails#trails_by_difficulty'
  get '/parks_by_location' => 'parks#parks_by_location'
  get '/parks_by_name' => 'parks#parks_by_name'
  get '/trails/:id/next', to: 'trails#next_trail'
  get '/trails/:id/previous', to: 'trails#previous_trail'

  get '/parks/:id/next', to: 'parks#next_park'
  get '/parks/:id/previous', to: 'parks#previous_park'



 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/facebook/callback' => 'sessions#facebook'
  #get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  

end

app/models/trail.rb
class Trail < ApplicationRecord
  
  belongs_to :park
  has_many :users, through: :comments
  has_many :comments, :dependent => :destroy
 
 mount_uploader :image, ImageUploader
 validates_presence_of :name, :distance, :date, :difficulty


 

 def self.search(search)
 # where("distance LIKE ? ", "#{search}") sqlite
 where("cast(distance as text) LIKE ?", "#{search}")
end

def self.search2(search)
  #where("difficulty LIKE ? ", "#{search}")
  where("cast(difficulty as text) LIKE ? ", "#{search}")
end
def next
  # if the first trail is greater the current one exists then return the next trail
  if next_trail = self.class.where("id > ?", id).first
    next_trail
  else
   Trail.first
  end
end

def previous
  # if the trail is less then current one exists then return the previous trail
  if previous_trail = self.class.where("id < ?", id).last
    previous_trail
  else
    Trail.last
  end
end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
    before_action :set_trail, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:index]

    def index
      @trails = Trail.all
      respond_to do |format|
        format.html {render :index}
        format.json {render json: @trails, status: 200}
      end
    end
  
    def new
      @trail = Trail.new
  
    end
  
    def show
      @comment = Comment.new
    if current_user
      @comment.user_id = current_user.id
    end
    respond_to do |format|
      format.html { render :show }
      format.json { render json:  @trail }
    end
  end 
    def next_trail
      @trail = Trail.find(params[:id])
      @next_trail = @trail.next
      render json: @next_trail
    end

    def previous_trail
      @trail = Trail.find(params[:id])
      @previous_trail = @trail.previous
      render json: @previous_trail
    end
  
    def create
      
      @park = Park.find(params[:trail][:park_id])
     
      @trail = @park.trails.build(trail_params)
      #raise params.inspect
      if @trail.save!
        flash[:msg] = "Trail created!"
        redirect_to trail_path(@trail.id)
  
      else
        render :new
      end
   
  end
  
    def edit
    end
  
    def update
      @trail.update(trail_params)
      if @trail.save!
        flash[:msg] = "Trail updated!"
        redirect_to trail_path(@trail)
      else
        render :edit
      end
  
    end

    def trails_by_distance
      list = Trail.search(params[:search]).order("created_at DESC")
      if !list.empty?
        @trails = list
      else
        flash[:notice] = "There are no trails matching the input."
        redirect_to trails_path
      end
    end

    def trails_by_difficulty
    list = Trail.search2(params[:search]).order("created_at DESC")
    if !list.empty?
      @trails = list
    else
      flash[:notice] = "There are no trails matching the input."
      redirect_to trails_path
    end
  end
  
    def destroy
      
     @trail.destroy
      flash[:msg] = "Trail deleted!"
      redirect_to trails_path
  
    end
  
    private
  
    def set_trail
      @trail = Trail.find(params[:id])
  
    end
  
    def trail_params
      params.require(:trail).permit(:name, :image, :remove_image, :distance, :date, :description, :difficulty, :user_id)
    end
  end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/_form.html.erb
<div class='parks-form'>
<%= form_for [@park, @trail] do |f| %>
    <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  
  <div class="field">
    <%= f.label "Notes" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.select :difficulty, ['Easy', 'Moderate', 'Difficult']%>
    </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
    <%= image_tag f.object.image.url %>
    <%= f.label :remove_image %>
    <%= f.check_box :remove_image %>
    
   
  <% end %><br><br>

    <%= f.hidden_field :user_id, :value => current_user.id%> 
    <%= f.hidden_field :park_id, :value => params[:park_id]%><br>

        <%= f.submit "Create Trail", class:"submit" %>
<% end %>

<% if @trail.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p> Error: </p>
          <ul>
            <% @trail.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
       <% end %>

       </div>

app/views/trails/edit.html.erb
<center><h1>Edit trail</h1></center>

<%= render 'form' %>

app/views/trails/index.html.erb
<div class="trails-index">
<div class='wrapper'>

<h1>All Trails</h1>
<% @trails.each do |trail| %>

<h2>Trail Name: <%= link_to trail.name, trail_path(trail), class:'name' %></h2>
<h4>Posted by: <%= link_to trail.park.user.name, user_path(trail.park.user) %></h4>
<h4 id="description-<%= trail.id %>">Notes:<%= truncate(trail.description, length:3)%></p>

<a href="#" class="js-more" data-id="<%= trail.id %>">Read more<span class=" glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
<hr />
<% end %>

</div>
</div>

app/views/trails/new.html.erb
<center><h1>Add a new trail</h1></center>
<%= render 'form' %>

app/views/trails/show.html.erb
<div id="trail">
   
<div class="container">
<div class="row">

<div class="col-md-5">
<br></br>
<%= image_tag @trail.image.url(:medium) if @trail.image?%>
</div>



<div class="col-md-5" id='trailPage'>

  <h2 class='trailName'>Trail Name: <%= @trail.name %></h2>
  <h3 class='trailPark'>Park Name: <%= link_to @trail.park.name, park_path(@trail.park) %></h3>


 <h4 class='trailDistance'>Distance:&nbsp;&nbsp;&nbsp;<%= @trail.distance %> miles</h4>
 <h4 class='trailDate'>Date:&nbsp;&nbsp;&nbsp;<%= @trail.date.strftime('%B, %d %Y') %></h4>
 <h4 class='trailDifficulty'>Difficulty: <%= @trail.difficulty %></h4>
  <h4 class='trailNotes'>Trail Notes: <%= @trail.description %></h4>
  
  
  <% if current_user == @trail.park.user %>
  <h4 id="trail-links">
      <%= link_to "Edit Trail", edit_trail_path(@trail), class: "edit-link" %>&nbsp;&nbsp;&nbsp;
     <%= link_to "Delete Trail", trail_path(@trail), method: :delete, data: { confirm: 'Are you sure?' }%>

    <% end %></h4>
    </div>
    </div>
    </div>

   
    
   <div class="box-div">
   </div>
    
    <section id='comments'>
    
      <div class='container'>
    <% if current_user %>
    <h4>Add a comment:</h4>
    <div class='new-comment'>
    <%= form_for @comment, url: trail_comments_path(@trail, @comment)  do |f| %>
        <p><strong>Content</strong> <%= f.text_area :body, class: 'commentBox form-control'  %></p>
        
        <%= f.hidden_field :user_id, :value => current_user.id%> 
        <%= f.hidden_field :trail_id, :value => :trail_id %>
        <button type="submit" class="btn btn-sm btn-primary">Create Comment</button>
      <% end %><br>
    
      </div>
      <% end %>
   </div>
  
    <h2><%= link_to "Comments:", trail_comments_path(@trail), class: "comment-link" %></h2>
    <section class='comment-sec'>
<% @trail.comments.each do |comment| %>
   
  <div class="well well-white" id="comment-<%= comment.id %>">
   <strong><%= comment.user.name %></strong> says: <br></br>
     <p><%= comment.body %></p>
     
</div>

<% end %>

</section>

 </div>
 
 </section>
  
  
  
  
 
  
  

app/views/trails/trails_by_difficulty.html.erb
<h2>Trails by difficulty:</h2><br><br>
<div class = "container">
<% @trails.order("created_at asc").each do |trail| %>
  <div class="row row-flex">
      <div class="col-md-6"><br></br>
        <%= image_tag trail.image.url(:medium) if trail.image? %><br><br>
        
      </div>

      
      

      <div class="col-md-4">
      <br />
      <h4> User: <%= link_to trail.park.user.name, user_path(trail.park.user) %> </h4>
      <h3>Trail:&nbsp;&nbsp;&nbsp;<%= link_to trail.name, trail_path(trail), class:'name' %></h3>
      <h3 >Distance:&nbsp;&nbsp;&nbsp;<%= trail.distance %> miles</h3>
      </div>
    
  </div>
  <hr />
<% end %>
</div>

app/views/trails/trails_by_distance.html.erb
<h2>Trails by distance:</h2><br><br>
<div class = "container">
<% @trails.order("created_at asc").each do |trail| %>

    <div class="row row-flex">
      <div class="col-md-6"><br></br>
        <%= image_tag trail.image.url(:medium) if trail.image? %><br><br>
        
      </div>

      
      

      <div class="col-md-4">
      
        <br />
        <h4> User: <%= link_to trail.park.user.name, user_path(trail.park.user) %> </h4>
        <h3>Trail:&nbsp;&nbsp;&nbsp;<%= link_to trail.name, trail_path(trail), class:'name' %></h3>
        <h3 >Distance:&nbsp;&nbsp;&nbsp;<%= trail.distance %> miles</h3>
      </div>
    
  </div>
  <hr />
<% end %>
</div>