config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do 
   shallow do 
    resources :parks do 
      resources :trails
      end 
     end 
    end 

     
         
      resources :trails do
        #shallow do
        resources :comments
   # end
   
  end

  resources :parks, only: [:index]

  resources :trails, only: [:index, :create] 

  get '/trails_by_distance' => 'trails#trails_by_distance'
  get '/trails_by_difficulty' => 'trails#trails_by_difficulty'
  get '/parks_by_location' => 'parks#parks_by_location'
  get '/parks_by_name' => 'parks#parks_by_name'
  get '/trails/:id/next', to: 'trails#next_trail'
  get '/trails/:id/previous', to: 'trails#previous_trail'

  get '/parks/:id/next', to: 'parks#next_park'
  get '/parks/:id/previous', to: 'parks#previous_park'



 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/facebook/callback' => 'sessions#facebook'
  #get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>  

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    </head>

  <body>
  
  <nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <% if logged_in? %>
            <a class="navbar-brand" href="/trails" style="color:white;">Parks-book</a>
           
          <% else %>
            <a class="navbar-brand" href="/" style="color:white;">Parks-book</a>
          <% end %>
      
    </div>
    <ul class="nav navbar-nav">
      
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown">Search <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><p class="search-t">Trails by distance</p>
          <%= form_tag('/trails_by_distance', :method => "get", id: "search-form") do %>
              <%= number_field_tag :search, params[:search], placeholder: " whole miles", class: "search-input" %>
              <%= submit_tag "Search", class: "btn-sm", :name => nil %>
          <% end %></li>
          <li><p class="search-t">Trails by difficulty</p>
          <%= form_tag('/trails_by_difficulty', :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: " Easy, Moderate, Hard", class: "search-input" %>
              <%= submit_tag "Search", class: "btn-sm", :name => nil %>
          <% end %></li>
          <li><p>Parks by location</p>
          <%= form_tag('/parks_by_location', :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], class: "search-input" %>
              <%= submit_tag "Search", class: "btn-sm", :name => nil %>
          <% end %></li>
          <li><p>Parks by name</p>
          <%= form_tag('/parks_by_name', :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], class: "search-input" %>
              <%= submit_tag "Search", class: "btn-sm", :name => nil %>
          <% end %></li>
        </ul>
      </li>
      </ul>
    <div class="collapse navbar-collapse" id="myNavbar">
      
      <ul class="nav navbar-nav navbar-right">
      
      <% if !logged_in? %>

        <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      
      <% end %>

      <% if current_user %>
      
      <li><%= link_to "Welcome, #{current_user.name}!", user_path(current_user) %></li>
    
      

               
           <li><%= link_to "Parks", parks_path%> </li>
          <li><%= link_to "Trails", trails_path%></li>
          <li><%= link_to "Log Out", logout_path%></li>
          
        <% end %>
        </ul>
    </div>
  </div>
</nav>



  <% if flash[:notice] %>
                <div class="alert alert-danger" role="alert"><%= flash[:notice] %></div>
              <% end %>

              <% if flash[:msg] %>
                <div class="alert alert-success" role="alert"><%= flash[:msg] %></div>
              <% end %>
              
              
    <%= yield %>

    


<!-- Footer -->
<footer class="text-center">
  
  <small>&copy; 2018 <strong>Parks-book </strong>All Rights Reserved.</small>
</footer>
      </div>

     
  </body>
</html>